### ISSUE TITLE
Cannot provide and consume data

### ISSUE THREAD

**Issue by barkalinowski** [european-dynamics-rnd/OneNet#16]
Hi,

we managed to establish connection with onenet system:
![image](https://github.com/european-dynamics-rnd/OneNet/assets/70036239/7146b1c3-df83-4f66-93d8-57ef46feb3c4)
We were able to do that by making Local API url public. 
Although we are not able to consume or provide data through the GUI.
Here is our request for providing data:
![image](https://github.com/european-dynamics-rnd/OneNet/assets/70036239/4f532446-781c-47bf-8017-2d23f1117c9e)
and here is response from the connector:
![image](https://github.com/european-dynamics-rnd/OneNet/assets/70036239/8a10523c-5529-4b58-9333-eceaec8fa782)
Very similar errors we are getting when we try to consume data. Is it something on your side or are we still doing something wrong?

**Comment by HeliasEurodyn** [comment]
Hello Bartosz,
It was a temporary issue that appeared due to a major version upgrade on Onenet last week. It is fixed now.
Everything works ok now.

**Comment by barkalinowski** [comment]
Hi Helias,
We have checked it and it is still not working. This time we have problems with lacking permission to perform consume or provide data:
![image](https://github.com/european-dynamics-rnd/OneNet/assets/70036239/f2587e75-a632-4451-91a9-f9baa040358e)
![image](https://github.com/european-dynamics-rnd/OneNet/assets/70036239/46753e13-b0a6-4647-8d11-d9dab4a44f66)

Maybe our accounts are somehow blocked?

**Comment by ferdinandobosco** [comment]
> Hello again,
> 
> It seems like we have managed to fix issue with providing data, but now we have problem with consuming data. Here is log file: [docker_be-dataapp-consumer_1-2023-06-14T08-03-56.log](https://github.com/european-dynamics-rnd/OneNet/files/11743326/docker_be-dataapp-consumer_1-2023-06-14T08-03-56.log)
> 
> Could you please check it?

Hi,
it seems related to the conversion of the data into the Orion Context Broker data model. 

Which kind of data are you providing? 

Can you please test a new entire workflow (create service, create data, subscribe and get)?

Thanks,
Ferdinando

**Comment by barkalinowski** [comment]
Hi,

thank you for your reply - I have tested new entire workflow and again the same error and problem. Log file does not change. Are there any other things we can check?

**Comment by barkalinowski** [comment]
Hello again,

theoretically providing and consuming data works for us right now, but we cannot download shared files. In logs we have this error:
![image](https://github.com/european-dynamics-rnd/OneNet/assets/70036239/3971805a-8ee5-40de-ba64-94e7107705fe)
I would like to ask you about verification of this error.

Additionally we would like to ask, why "content" field is missing in this response and what is the cause of this situation:
![image](https://github.com/european-dynamics-rnd/OneNet/assets/70036239/e51a2f54-fc13-4235-b7bc-db322641398d)

Also full log file can be found here: 
[flex-docker-onenet.log](https://github.com/european-dynamics-rnd/OneNet/files/12027198/flex-docker-onenet.log)

**Comment by christos-aslamatzidis** [comment]
Hello, 
can you provide us with more information ?
If I understand right you are able to upload a file and you can downloaded but you can consume data from other users.
If this is the case:
1) confirm that your connection settings are right (in the dashboard there is a connection checker -> should be green)
2 ) give us information about the file that you try to download (user, offered service  and specific file) . Maybe some users have some changes in their installation and you come up with  this issue.
Best regards,
Christos

**Comment by barkalinowski** [comment]
Hello Christos,

1. Yes, we have established connection:
![image](https://github.com/european-dynamics-rnd/OneNet/assets/70036239/d632db87-bad0-409d-b6a7-980de2dade1f)
2. Example file:
user: kamil.starzewski
offered service: 3c1fe571-4381-492a-99f3-a1479b940cd8
file: aee04a31-173b-40b6-9064-c70c1e7c0a1d

If kamil.starzewski provides data, for bartosz.kalinowski to consume, the same error is happening.

**Comment by christos-aslamatzidis** [comment]
Hello again , the file that you send me as an example is created by you. So I want to ask if you are able to downloaded for your own .
If one of you can not download his own files the problem maybe is relevant to this user.  If both of you can download your own files you need to check for network issues. (Try to exchange a file when you are in the same network or ensure that data app and ecc url are public and mapped to static ip for both users)
Also I have added a request for this offered service as tteesstt user to see if I can consume it.
Thank you ,
Christos

**Comment by barkalinowski** [comment]
Hi Christos,
I have accepted your request, try to consume data. I have also tried to download a file as bartosz.kalinowski(which was the provider) and I also cannot do it. So provider cannot download the file, which he provided and consumer cannot download a provided file. What can we do about it?

Regarding network issues I am quite sure, everything is sorted out on our side. Every IP used is static and open to public, we confirmed this with Helias, Ferdinando and Vassilis some time ago. Both accounts (bartosz.kalinowski and kamil.starzewski) use the same configuration of connection also.

**Comment by christos-aslamatzidis** [comment]
Can you make a last check please ? Can you check if all the containers are up and running correctly ?
Thank you in advance, Christos

**Comment by barkalinowski** [comment]
Sure Christos, here you go:
![image](https://github.com/european-dynamics-rnd/OneNet/assets/70036239/3e8d9e8e-ba1d-4685-a8b8-0b144047cc82)

**Comment by barkalinowski** [comment]
Hi @christos-aslamatzidis are there any new updates what can we do about our problem?

**Comment by barkalinowski** [comment]
Hi Ferdinando,

well, yes both of the users(provider and consumer) are configured on the same VM and have the same connetor settings. Is this correct or this the cause of our problems?
Also how are we suppose to check if we use unique connector? You mean unique for each of the user? And how we can check if ecc-provider url is correctly setup? 
Here is our setup of the connector settings(for both users is the same):
![image](https://github.com/european-dynamics-rnd/OneNet/assets/70036239/da98b721-cf84-4644-86ca-b6ed7317abd3)
First three urls are public domains connected through proxy to VM, which IP address is in the last url, and every docker container is installed on this VM.

**Comment by ferdinandobosco** [comment]
Hi again,
you can use the same connector with two different users. No problem with that.

We have done some additional tests. It seems that ECC is not reachable. We receive a 403 forbidden. It looks like it requires authentication or something, but it shouldn't be.

![MicrosoftTeams-image](https://github.com/european-dynamics-rnd/OneNet/assets/7289897/97058f07-c77b-469c-b747-89a3e536dd26)

**Comment by barkalinowski** [comment]
Hi Ferdinando,

Thank you for your response. I would like to ask you what should we expect from this request? We were trying on our side, internally and here are our observations:

- <ip where docker containers are installed>:8889 is mapped under atlex-ecc-onenet.tt-cloud.com.pl domain, so when we try to enter this url this is what we get:
![image](https://github.com/european-dynamics-rnd/OneNet/assets/70036239/5b597d02-0f8e-442b-ac6e-bde2f4c73b1f)
the same happens when I add "/data" as suffix
- next to Ecc Url tab, there is this "Help" button, but in there, it is indicated, that we need to put 8090 port(not 8889) to check version and this is what we get when I put ip with this 8090 port:
![image](https://github.com/european-dynamics-rnd/OneNet/assets/70036239/aac2360a-0cca-4894-9529-e093cc0374d0)
![image](https://github.com/european-dynamics-rnd/OneNet/assets/70036239/52bf86d5-bd49-4ca8-9edd-04887f624362)
- and now we see the problem for our domain, which is,  just a remainder, mapped under 8889, so we cannot really check the version for ecc publicly, because we will pass two ports in the url 172.16.129.109:8889:8090/about/version
- regarding response from the url you passed to the browser it looks like this for us:
![image](https://github.com/european-dynamics-rnd/OneNet/assets/70036239/a2575055-0ab2-44f6-8483-f0f29c514e71)
So, yeah there most likely is the problem on our side, but we would like to know, what view we should expect when we put this url to the browser.

**Comment by ferdinandobosco** [comment]
Hi,
at the 8889 you should receive a Jetty error like this:
![image](https://github.com/european-dynamics-rnd/OneNet/assets/7289897/15779008-f347-4354-86e8-4faf6003d7db)

With /data, you should download a JSON like this:

```
--AyivDgLGvyZ-0mrbPbgiUorzq0vAsIk4w
Content-Disposition: form-data; name="header"
Content-Length: 1204
Content-Type: application/ld+json

{
  "@context" : {
    "ids" : "https://w3id.org/idsa/core/",
    "idsc" : "https://w3id.org/idsa/code/"
  },
  "@type" : "ids:RejectionMessage",
  "@id" : "https://w3id.org/idsa/autogen/rejectionMessage/8fd1eeeb-d7f6-490f-b5f1-26790431914a",
  "ids:rejectionReason" : {
    "@id" : "https://w3id.org/idsa/code/MALFORMED_MESSAGE"
  },
  "ids:issuerConnector" : {
    "@id" : "https://w3id.org/engrd/connector/"
  },
  "ids:recipientConnector" : [ {
    "@id" : "http://w3id.org/engrd/connector"
  } ],
  "ids:senderAgent" : {
    "@id" : "https://w3id.org/engrd/connector/"
  },
  "ids:recipientAgent" : [ ],
  "ids:securityToken" : {
    "@type" : "ids:DynamicAttributeToken",
    "@id" : "https://w3id.org/idsa/autogen/dynamicAttributeToken/a6a38918-80bc-4364-bcc0-b5eaaeb50b8e",
    "ids:tokenFormat" : {
      "@id" : "https://w3id.org/idsa/code/JWT"
    },
    "ids:tokenValue" : "DummyTokenValue"
  },
  "ids:modelVersion" : "4.1.0",
  "ids:issued" : {
    "@value" : "2023-07-24T15:11:24.819Z",
    "@type" : "http://www.w3.org/2001/XMLSchema#dateTimeStamp"
  },
  "ids:correlationMessage" : {
    "@id" : "https://w3id.org/idsa/autogen/rejectionMessage/3b16bb99-f96a-4d0b-b06e-e7fe5f49f290"
  }
}
--AyivDgLGvyZ-0mrbPbgiUorzq0vAsIk4w--
```

**Comment by barkalinowski** [comment]
Hi Ferdinando,

we have managed to fix 8889 port and we get exactly what you indicated in the previous post(we get Jetty error and after addition of "/data" we download JSON file). Unfortunately it did not solve our problems regarding consumption of the data. We get exactly the same error as previously. It turned out that proxy was trying to connect to docker through 8889 with http - that was causing the problem. So we changed also from http to https for local api and data app ports, but it switched off our connection, so we came back to http connection for these two. What can be our next steps regarding this case?

**Comment by barkalinowski** [comment]
Hi Ferdinando,
I would like to remind you about problems we have. We still get 500:
![image](https://github.com/european-dynamics-rnd/OneNet/assets/70036239/ed8f6e7b-45de-49ae-b5c9-4470800f4610)
